### ISSUE TITLE
Suggestion: rename the project to goqu

### ISSUE THREAD

**Issue by dlyongemallo** [itsubaki/q#24]
I propose to rename this project to goqu for the following reasons:
* it is much easier to find on a search engine
* it makes it obvious what the project is (**go qu**antum computation simulator)
* it is much more memorable (and alludes to a popular manga/anime series)

Possible cons:
* there are other projects named goqu (a popular one being an SQL query library for golang)
* there is already an abandoned go quantum computer simulator named [goqu](https://github.com/cco3/goqu)

There's no reason why two projects can't have the same name, especially if they are in different areas. (No one will confuse an SQL query library for a quantum simulator.) 

The other goqu quantum simulator project has been abandoned for a long time. I was one of its main contributors. @cco3 is the repo owner so if you like my suggestion, we'd have to ask him for permission to use the name. I like the name so much that I think it's a pity it's not being used for an active Go quantum simulator project.

**Comment by itsubaki** [comment]
Thank you for suggestion.
Certainly, the name `q` may not be the best. but I'm not considering changing it right now for the following reasons:

1. There are already users.
2. It ranks at the top when searching for 'quantum golang' on Google and GitHub.
3. As you mentioned, 'goqu' is a well-known query builder and cloud cause confusion.
