### ISSUE TITLE
Real time discussion

### ISSUE THREAD

**Issue by sah4ez** [itsubaki/q#8]
May be create chat somewhere, as example in slack or gitter?

**Comment by itsubaki** [comment]
OK:) I will create workspace in slack.

**Comment by itsubaki** [comment]
i created https://im-interested-in-qc.slack.com/ and invited you.

**Comment by itsubaki** [comment]
Thanks for joined!

but
I think it's better to have ideas and discussions in open place.
Because everyone can verify whether it is a good idea.

What do you think?
